spring:
  application:
    name: servicio-items
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      itemsCB:
        base-config: defecto
      itemsTL:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      itemsTL:
        base-config: defecto

logging:
  level:
    com.formacionbdi.springboot.app.item: DEBUG